# Generated by Django 6.1.1 on 2026-09-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('department_id', models.IntegerField()),
            ],
        ),
    ]
