# Generated by Django 6.1.1 on 2026-09-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='departmentName',
            new_name='DepartmentName',
        ),
    ]
