# Generated by Django 6.1.1 on 2026-09-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_id',
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.department'),
        ),
    ]
